export class Filters {
    static salaries = [
        {'value': 'nn', 'display': 'Unités non employeuses'},
        {'value': '00', 'display': '0 salarié'},
        {'value': '01', 'display': '1 ou 2 salariés'},
        {'value': '02', 'display': '3 à 5 salariés'},
        {'value': '03', 'display': '6 à 9 salariés'},
        {'value': '11', 'display': '10 à 19 salariés'},
        {'value': '12', 'display': '20 à 49 salariés'},
        {'value': '21', 'display': '50 à 99 salariés'},
        {'value': '22', 'display': '100 à 199 salariés'},
        {'value': '31', 'display': '200 à 249 salariés'},
        {'value': '32', 'display': '250 à 499 salariés'},
        {'value': '41', 'display': '500 à 999 salariés'},
        {'value': '42', 'display': '1 000 à 1 999 salariés'},
        {'value': '51', 'display': '2 000 à 4 999 salariés'},
        {'value': '52', 'display': '5 000 à 9 999 salariés'},
        {'value': '53', 'display': '10 000 salariés et plus'},
    ];

    static categories = [
        {'value': 'PME', 'display': 'Petite ou Moyenne Entreprise'},
        {'value': 'ETI', 'display': 'Entreprise de Taille Intermédiaire'},
        {'value': 'GE', 'display': 'Grande Entreprise'},
    ];

    static nj = [
        {'value': '6540', 'display': 'Société civile immobilière'},
        {'value': '5499', 'display': 'Société à responsabilité limitée (sans autre indication)'},
        {'value': '9220', 'display': 'Association déclarée'},
        {'value': '5710', 'display': 'SAS, société par actions simplifiée'},
        {'value': '5498', 'display': 'SARL unipersonnelle'},
        {
            'value': '5720',
            'display': 'Société par actions simplifiée à associé unique ou société par actions simplifiée unipersonnelle'
        },
        {'value': '6599', 'display': 'Autre société civile'},
        {'value': '9110', 'display': 'Syndicat de copropriété'},
        {'value': '7210', 'display': 'Commune et commune nouvelle'},
        {'value': '6598', 'display': 'Exploitation agricole à responsabilité limitée'},
        {'value': '5599', 'display': 'SA à conseil d\'administration (s.a.i.)'},
        {'value': '3220', 'display': 'Société étrangère non immatriculée au RCS'},
        {'value': '5202', 'display': 'Société en nom collectif'},
        {'value': '2110', 'display': 'Indivision entre personnes physiques'},
        {'value': '6541', 'display': 'Société civile immobilière de construction-vente'},
        {'value': '6533', 'display': 'Groupement agricole d\'exploitation en commun (GAEC)'},
        {'value': '6589', 'display': 'Société civile de moyens'},
        {'value': '5485', 'display': 'Société d\'exercice libéral à responsabilité limitée'},
        {'value': '6597', 'display': 'Société civile d\'exploitation agricole'},
        {'value': '6534', 'display': 'Groupement foncier agricole'},
        {'value': '5485', 'display': 'Société d\'exercice libéral à responsabilité limitée'},
        {'value': '6597', 'display': 'Société civile d\'exploitation agricole'},
        {'value': '6534', 'display': 'Groupement foncier agricole'},
        {'value': '7361', 'display': 'Centre communal d\'action sociale'},
        {'value': '3120', 'display': 'Société commerciale étrangère immatriculée au RCS'},
        {'value': '9260', 'display': 'Association de droit local (Bas-Rhin, Haut-Rhin et Moselle)'},
        {'value': '2210', 'display': 'Société créée de fait entre personnes physiques'},
        {'value': '2900', 'display': 'Autre groupement de droit privé non doté de la personnalité morale'},
        {'value': '6316', 'display': 'Coopérative d\'utilisation de matériel agricole en commun (CUMA)'},
        {'value': '7210', 'display': 'Commune'},
        {'value': '5699', 'display': 'SA à directoire (s.a.i.)'},
        {'value': '6220', 'display': 'Groupement d\'intérêt économique (GIE)'},
        {'value': '5510', 'display': 'SA nationale à conseil d\'administration'},
        {'value': '7172', 'display': 'Service déconcentré de l\'État à compétence (inter) départementale'},
        {'value': '7331', 'display': 'Établissement public local d\'enseignement'},
        {'value': '7364', 'display': 'Établissement d\'hospitalisation'},
        {'value': '6596', 'display': 'Caisse de crédit agricole mutuel'},
        {'value': '6536', 'display': 'Groupement forestier'},
        {'value': '5485', 'display': 'Association déclarée, reconnue d\'utilité publique'},
        {'value': '6317', 'display': 'Société coopérative agricole'},
        {'value': '8210', 'display': 'Mutuelle'},
        {'value': '7353', 'display': 'Syndicat intercommunal à vocation unique (SIVU)'},
        {'value': '9223', 'display': 'Groupement d\'employeurs'},
        {'value': '7323', 'display': 'Association foncière de remembrement'},
        {'value': '7362', 'display': 'Caisse des écoles'},
        {
            'value': '4120',
            'display': 'Établissement public national à caractère industriel ou commercial non doté d\'un comptable public'
        },
        {'value': '7321', 'display': 'Association syndicale autorisée'},
        {'value': '7220', 'display': 'Département'},
        {'value': '8310', 'display': 'Comité central d\'entreprise'},
        {'value': '7171', 'display': 'Service déconcentré de l\'État à compétence (inter) régionale'},
        {'value': '7389', 'display': 'Établissement public national à caractère administratif'},
        {'value': '8410', 'display': 'Syndicat de salariés'},
        {'value': '5785', 'display': 'Société d\'exercice libéral par action simplifiée'},
        {'value': '8420', 'display': 'Syndicat patronal'},
        {'value': '7346', 'display': 'Communauté de communes'},
        {'value': '7366', 'display': 'Établissement public local social et médico-social'},
        {'value': '9150', 'display': 'Association syndicale libre'},
        {'value': '6565', 'display': 'SCP de notaires'},
        {'value': '9900', 'display': 'Autre personne morale de droit privé'},
        {'value': '5560', 'display': 'Autre SA coopérative à conseil d\'administration'},
        {'value': '7383', 'display': 'Établissement public national à caractère scientifique culturel et professionnel'},
        {'value': '9300', 'display': 'Fondation'},
        {'value': '6561', 'display': 'SCP d\'avocats'},
        {'value': '5515', 'display': 'SA d\'économie mixte à conseil d\'administration'},
        {'value': '6595', 'display': 'Caisse locale de crédit mutuel'},
        {'value': '8311', 'display': 'Comité d\'établissement'},
        {'value': '3290', 'display': 'Autre personne morale de droit étranger'},
        {'value': '6411', 'display': 'Société d\'assurance à forme mutuelle'},
        {'value': '7354', 'display': 'Syndicat mixte fermé'},
        {'value': '5192', 'display': 'Société coopérative de banque populaire'},
        {'value': '5308', 'display': 'Société en commandite par actions'},
        {'value': '5660', 'display': 'Autre SA coopérative à directoire'},
        {'value': '2700', 'display': 'Paroisse hors zone concordataire'},
        {'value': '8250', 'display': 'Assurance mutuelle agricole'},
        {'value': '8110', 'display': 'Régime général de la Sécurité Sociale'},
        {'value': '6585', 'display': 'Autre société civile professionnelle'},
        {
            'value': '5470',
            'display': 'Société de Participations Financiere de Prof Libérale Société à responsabilité limitée (SPFPL SARL)'
        },
        {'value': '4140', 'display': 'Établissement public local à caractère industriel ou commercial'},
        {'value': '5460', 'display': 'Autre SARL coopérative'},
        {'value': '8450', 'display': 'Ordre professionnel ou assimilé'},
        {'value': '5194', 'display': 'Caisse (fédérale) de crédit mutuel'},
        {'value': '7430', 'display': 'Établissement public des cultes d\'Alsace-Lorraine'},
        {'value': '9210', 'display': 'Association non déclarée'},
        {'value': '7381', 'display': 'Organisme consulaire'},
        {'value': '7345', 'display': 'Syndicat intercommunal à vocation multiple (SIVOM)'},
        {'value': '5458', 'display': 'SARL coopérative ouvrière de production (SCOP)'},
        {'value': '6573', 'display': 'SCP d\'infirmiers'},
        {'value': '5306', 'display': 'Société en commandite simple'},
        {'value': '7385', 'display': 'Autre établissement public national administratif à compétence territoriale limitée'},
        {'value': '9240', 'display': 'Congrégation'},
        {'value': '6571', 'display': 'SCP de médecins'},
        {'value': '5410', 'display': 'SARL nationale'},
        {'value': '6576', 'display': 'SCP de vétérinaires'},
        {'value': '6542', 'display': 'Société civile d\'attribution'},
        {'value': '8490', 'display': 'Autre organisme professionnel'},
        {'value': '7179', 'display': '(Autre) Service déconcentré de l\'État à compétence territoriale'},
        {'value': '7355', 'display': 'Syndicat mixte ouvert'},
        {'value': '2310', 'display': 'Société en participation entre personnes physiques'},
        {'value': '6538', 'display': 'Groupement foncier et rural'},
        {'value': '7348', 'display': 'Communauté d\'agglomération'},
        {'value': '6564', 'display': 'SCP d\'huissiers'},
        {'value': '2120', 'display': 'Indivision avec personne morale'},
        {'value': '7313', 'display': 'Section de commune'},
    ];

    static tca = [
        {'value': '0', 'display': 'Moins de 0,5 million d\'euros'},
        {'value': '1', 'display': 'De 0,5 à moins de 1 million d\'euros'},
        {'value': '2', 'display': 'De 1 million à moins de 2 millions d\'euros'},
        {'value': '3', 'display': 'De 2 millions à moins de 5 millions d\'euros'},
        {'value': '4', 'display': 'De 5 millions à moins de 10 millions d\' euros'},
        {'value': '5', 'display': 'De 10 millions à moins de 20 millions d\'euros'},
        {'value': '6', 'display': 'De 20 millions à moins de 50 millions d\'euros'},
        {'value': '7', 'display': 'De 50 millions à moins de 100 millions d\'euros'},
        {'value': '8', 'display': 'De 100 millions à moins de 200 millions d\'euros'},
        {'value': '9', 'display': '200 millions d\'euros ou plus'},
    ];

    static depet = [
        {'value': '01', 'display': 'Ain'},
        {'value': '02', 'display': 'Aisne'},
        {'value': '03', 'display': 'Allier'},
        {'value': '05', 'display': 'Hautes-Alpes'},
        {'value': '04', 'display': 'Alpes-de-Haute-Provence'},
        {'value': '06', 'display': 'Alpes-Maritimes'},
        {'value': '07', 'display': 'Ardèche'},
        {'value': '08', 'display': 'Ardennes'},
        {'value': '09', 'display': 'Ariège'},
        {'value': '10', 'display': 'Aube'},
        {'value': '11', 'display': 'Aude'},
        {'value': '12', 'display': 'Aveyron'},
        {'value': '13', 'display': 'Bouches-du-Rhône'},
        {'value': '14', 'display': 'Calvados'},
        {'value': '15', 'display': 'Cantal'},
        {'value': '16', 'display': 'Charente'},
        {'value': '17', 'display': 'Charente-Maritime'},
        {'value': '18', 'display': 'Cher'},
        {'value': '19', 'display': 'Corrèze'},
        {'value': '2a', 'display': 'Corse-du-sud'},
        {'value': '2b', 'display': 'Haute-corse'},
        {'value': '21', 'display': 'Côte-d\'or'},
        {'value': '22', 'display': 'Côtes-d\'armor'},
        {'value': '23', 'display': 'Creuse'},
        {'value': '24', 'display': 'Dordogne'},
        {'value': '25', 'display': 'Doubs'},
        {'value': '26', 'display': 'Drôme'},
        {'value': '27', 'display': 'Eure'},
        {'value': '28', 'display': 'Eure-et-Loir'},
        {'value': '29', 'display': 'Finistère'},
        {'value': '30', 'display': 'Gard'},
        {'value': '31', 'display': 'Haute-Garonne'},
        {'value': '32', 'display': 'Gers'},
        {'value': '33', 'display': 'Gironde'},
        {'value': '34', 'display': 'Hérault'},
        {'value': '35', 'display': 'Ile-et-Vilaine'},
        {'value': '36', 'display': 'Indre'},
        {'value': '37', 'display': 'Indre-et-Loire'},
        {'value': '38', 'display': 'Isère'},
        {'value': '39', 'display': 'Jura'},
        {'value': '40', 'display': 'Landes'},
        {'value': '41', 'display': 'Loir-et-Cher'},
        {'value': '42', 'display': 'Loire'},
        {'value': '43', 'display': 'Haute-Loire'},
        {'value': '44', 'display': 'Loire-Atlantique'},
        {'value': '45', 'display': 'Loiret'},
        {'value': '46', 'display': 'Lot'},
        {'value': '47', 'display': 'Lot-et-Garonne'},
        {'value': '48', 'display': 'Lozère'},
        {'value': '49', 'display': 'Maine-et-Loire'},
        {'value': '50', 'display': 'Manche'},
        {'value': '51', 'display': 'Marne'},
        {'value': '52', 'display': 'Haute-Marne'},
        {'value': '53', 'display': 'Mayenne'},
        {'value': '54', 'display': 'Meurthe-et-Moselle'},
        {'value': '55', 'display': 'Meuse'},
        {'value': '56', 'display': 'Morbihan'},
        {'value': '57', 'display': 'Moselle'},
        {'value': '58', 'display': 'Nièvre'},
        {'value': '59', 'display': 'Nord'},
        {'value': '60', 'display': 'Oise'},
        {'value': '61', 'display': 'Orne'},
        {'value': '62', 'display': 'Pas-de-Calais'},
        {'value': '63', 'display': 'Puy-de-Dôme'},
        {'value': '64', 'display': 'Pyrénées-Atlantiques'},
        {'value': '65', 'display': 'Hautes-Pyrénées'},
        {'value': '66', 'display': 'Pyrénées-Orientales'},
        {'value': '67', 'display': 'Bas-Rhin'},
        {'value': '68', 'display': 'Haut-Rhin'},
        {'value': '69', 'display': 'Rhône'},
        {'value': '70', 'display': 'Haute-Saône'},
        {'value': '71', 'display': 'Saône-et-Loire'},
        {'value': '72', 'display': 'Sarthe'},
        {'value': '73', 'display': 'Savoie'},
        {'value': '74', 'display': 'Haute-Savoie'},
        {'value': '75', 'display': 'Paris'},
        {'value': '76', 'display': 'Seine-Maritime'},
        {'value': '77', 'display': 'Seine-et-Marne'},
        {'value': '78', 'display': 'Yvelines'},
        {'value': '79', 'display': 'Deux-Sèvres'},
        {'value': '80', 'display': 'Somme'},
        {'value': '81', 'display': 'Tarn'},
        {'value': '82', 'display': 'Tarn-et-Garonne'},
        {'value': '83', 'display': 'Var'},
        {'value': '84', 'display': 'Vaucluse'},
        {'value': '85', 'display': 'Vendée'},
        {'value': '86', 'display': 'Vienne'},
        {'value': '87', 'display': 'Haute-Vienne'},
        {'value': '88', 'display': 'Vosges'},
        {'value': '89', 'display': 'Yonne'},
        {'value': '90', 'display': 'Territoire de Belfort'},
        {'value': '91', 'display': 'Essonne'},
        {'value': '92', 'display': 'Hauts-de-Seine'},
        {'value': '93', 'display': 'Seine-Saint-Denis'},
        {'value': '94', 'display': 'Val-de-Marne'},
        {'value': '95', 'display': 'Val-d\'oise'},
        {'value': '976', 'display': 'Mayotte'},
        {'value': '971', 'display': 'Guadeloupe'},
        {'value': '973', 'display': 'Guyane'},
        {'value': '972', 'display': 'Martinique'},
        {'value': '974', 'display': 'Réunion'},
    ];

    static township = [
        {'value': 'PARIS 1', 'display': 'PARIS 1'},
        {'value': 'PARIS 2', 'display': 'PARIS 2'},
        {'value': 'PARIS 3', 'display': 'PARIS 3'},
        {'value': 'PARIS 4', 'display': 'PARIS 4'},
        {'value': 'PARIS 5', 'display': 'PARIS 5'},
        {'value': 'PARIS 6', 'display': 'PARIS 6'},
        {'value': 'PARIS 7', 'display': 'PARIS 7'},
        {'value': 'PARIS 8', 'display': 'PARIS 8'},
        {'value': 'PARIS 9', 'display': 'PARIS 9'},
        {'value': 'PARIS 10', 'display': 'PARIS 10'},
        {'value': 'PARIS 11', 'display': 'PARIS 11'},
        {'value': 'PARIS 12', 'display': 'PARIS 12'},
        {'value': 'PARIS 13', 'display': 'PARIS 13'},
        {'value': 'PARIS 14', 'display': 'PARIS 14'},
        {'value': 'PARIS 15', 'display': 'PARIS 15'},
        {'value': 'PARIS 16', 'display': 'PARIS 16'},
        {'value': 'PARIS 17', 'display': 'PARIS 17'},
        {'value': 'PARIS 19', 'display': 'PARIS 19'},
        {'value': 'PARIS 20', 'display': 'PARIS 20'},
        {'value': 'SAINT DENIS', 'display': 'SAINT DENIS'},
        {'value': 'TOULOUSE', 'display': 'TOULOUSE'},
        {'value': 'NICE', 'display': 'NICE'},
        {'value': 'BORDEAUX', 'display': 'BORDEAUX'},
        {'value': 'MONTPELLIER', 'display': 'MONTPELLIER'},
        {'value': 'NANTES', 'display': 'NANTES'},
        {'value': 'STRASBOURG', 'display': 'STRASBOURG'},
        {'value': 'LILLE', 'display': 'LILLE'},
        {'value': 'AIX EN PROVENCE', 'display': 'AIX EN PROVENCE'},
        {'value': 'RENNES', 'display': 'RENNES'},
        {'value': 'GRENOBLE', 'display': 'GRENOBLE'},
        {'value': 'FORT DE FRANCE', 'display': 'FORT DE FRANCE'},
        {'value': 'BOULOGNE BILLANCOURT', 'display': 'BOULOGNE BILLANCOURT'},
        {'value': 'NIMES', 'display': 'NIMES'},
        {'value': 'CANNES', 'display': 'CANNES'},
        {'value': 'SAINT ETIENNE', 'display': 'SAINT ETIENNE'},
        {'value': 'TOULON', 'display': 'TOULON'},
        {'value': 'ANNECY', 'display': 'ANNECY'},
        {'value': 'DIJON', 'display': 'DIJON'},
        {'value': 'PERPIGNAN', 'display': 'PERPIGNAN'},
        {'value': 'REIMS', 'display': 'REIMS'},
        {'value': 'NEUILLY SUR SEINE', 'display': 'NEUILLY SUR SEINE'},
        {'value': 'MONTREUIL', 'display': 'MONTREUIL'},
        {'value': 'CLERMONT FERRAND', 'display': 'CLERMONT FERRAND'},
        {'value': 'LYON 2EME', 'display': 'LYON 2EME'},
        {'value': 'LYON 3EME', 'display': 'LYON 3EME'},
        {'value': 'LYON 6EME', 'display': 'LYON 6EME'},
        {'value': 'LYON 7EME', 'display': 'LYON 7EME'},
        {'value': 'ROUEN', 'display': 'ROUEN'},
        {'value': 'VILLEURBANNE', 'display': 'VILLEURBANNE'},
        {'value': 'ANTIBES', 'display': 'ANTIBES'},
        {'value': 'TOURS', 'display': 'TOURS'},
        {'value': 'AVIGNON', 'display': 'AVIGNON'},
        {'value': 'ANGERS', 'display': 'ANGERS'},
        {'value': 'MARSEILLE 1', 'display': 'MARSEILLE 1'},
        {'value': 'MARSEILLE 6', 'display': 'MARSEILLE 6'},
        {'value': 'MARSEILLE 8', 'display': 'MARSEILLE 8'},
        {'value': 'METZ', 'display': 'METZ'},
        {'value': 'NANCY', 'display': 'NANCY'},
        {'value': 'LE MANS', 'display': 'LE MANS'},
        {'value': 'CAEN', 'display': 'CAEN'},
        {'value': 'BESANCON', 'display': 'BESANCON'},
        {'value': 'LIMOGES', 'display': 'LIMOGES'},
        {'value': 'SAINT PAUL', 'display': 'SAINT PAUL'},
        {'value': 'AMIENS', 'display': 'AMIENS'},
        {'value': 'BREST', 'display': 'BREST'},
        {'value': 'VERSAILLES', 'display': 'VERSAILLES'},
        {'value': 'LE HAVRE', 'display': 'LE HAVRE'},
        {'value': 'COURBEVOIE', 'display': 'COURBEVOIE'},
        {'value': 'ORLEANS', 'display': 'ORLEANS'},
        {'value': 'LA ROCHELLE', 'display': 'LA ROCHELLE'},
        {'value': 'MULHOUSE', 'display': 'MULHOUSE'},
        {'value': 'LEVALLOIS PERRET', 'display': 'LEVALLOIS PERRET'},
        {'value': 'BEZIERS', 'display': 'BEZIERS'},
        {'value': 'SAINT MAUR DES FOSSES', 'display': 'SAINT MAUR DES FOSSES'},
        {'value': 'SAINT PIERRE', 'display': 'SAINT PIERRE'},
        {'value': 'PAU', 'display': 'PAU'},
        {'value': 'ASNIERES SUR SEINE', 'display': 'ASNIERES SUR SEINE'},
        {'value': 'BAIE MAHAULT', 'display': 'BAIE MAHAULT'},
        {'value': 'AUBERVILLIERS', 'display': 'AUBERVILLIERS'},
        {'value': 'VALENCE', 'display': 'VALENCE'},
        {'value': 'ROUBAIX', 'display': 'ROUBAIX'},
        {'value': 'AJACCIO', 'display': 'AJACCIO'},
        {'value': 'ARGENTEUIL', 'display': 'ARGENTEUIL'},
        {'value': 'NANTERRE', 'display': 'NANTERRE'},
        {'value': 'POITIERS', 'display': 'POITIERS'},
        {'value': 'RUEIL MALMAISON', 'display': 'RUEIL MALMAISON'},
        {'value': 'MERIGNAC', 'display': 'MERIGNAC'},
        {'value': 'HYERES', 'display': 'HYERES'},
        {'value': 'SAINT MARTIN', 'display': 'SAINT MARTIN'},
        {'value': 'LE LAMENTIN', 'display': 'LE LAMENTIN'},
        {'value': 'CAYENNE', 'display': 'CAYENNE'},
        {'value': 'NARBONNE', 'display': 'NARBONNE'},
        {'value': 'PANTIN', 'display': 'PANTIN'},
        {'value': 'ISSY LES MOULINEAUX', 'display': 'ISSY LES MOULINEAUX'},
        {'value': 'QUIMPER', 'display': 'QUIMPER'},
        {'value': 'FREJUS', 'display': 'FREJUS'},
        {'value': 'SAINT OUEN', 'display': 'SAINT OUEN'},
        {'value': 'COLMAR', 'display': 'COLMAR'},
        {'value': 'CAGNES SUR MER', 'display': 'CAGNES SUR MER'},
    ];
}
